### PR TITLE
Fix redis concurrency and invalidation

### LINKED ISSUE #77: Cache Invalidation Not Working
**Describe the bug**
There's an issue with caching. Seems like the cache doesn't get invalidated properly.
When you log out and old user, then sign in a new user, you still see details of the old users account.

**To Reproduce**
1. Sign up or log in
2. Click on 'logout' button after logging in
3. visit url for intern dashboard.'
4. User is still logged in.

### PR DESCRIPTION
**Pull request by Sidragon123**
Implemented the following:

1. getToken utility function to modularise fetching of id from session-specific cookies
2. Complete invalidation of user-specific cache items when a user logs out
3. Updated redis key naming syntax to "key-id" instead of "key" for user-specific info
4. Added invalidation support for the new syntax when the db is updated
5. Removed some redundant mentor code
6. Avoids concurrenct user issues and cache backup

### CODE REVIEW

File: Controllers/userController.js [hunk 1]
```diff
@@ -165,10 +172,14 @@ const logout = async (req, res) => {
 // the app know whether or not a user is logged in.
 const authorized = async (req, res) => {
   try {
-    let userInfo = await redisClient.GET("UserInfo");
+    const token = getToken.getToken(req);
+    let userInfo = await redisFunctions.cacheGetUserInfo(token);
     if (!userInfo) {
       logger.info("Auth not found in cache");
-      await redisClient.SET("UserInfo", JSON.stringify(res.locals.user));
+      await redisClient.SET(
```
Comment (gbudjeakp) [inline Controllers/userController.js]: I thought we said caching this could be a security risk? Do we still wanna do that?

File: utility/getToken/getToken.js [hunk 2]
```diff
@@ -0,0 +1,9 @@
+const jwt = require("jsonwebtoken");
+const getToken = (req) => {
+  const { authToken } = req.cookies;
+  const { id } = jwt.verify(authToken, process.env.JWT_SECRET);
```
Comment (gbudjeakp) [inline utility/getToken/getToken.js]: Can we have this also return the user name as well? So basically it return. So we grab the user name from it as well.
There are place where we use the username for example the `assignFeedBack` controller uses it.

**Review by gbudjeakp — CHANGES_REQUESTED** [review]

File: Controllers/userController.js (hunk 1 above)
Comment (Sidragon123) [reply Controllers/userController.js]: I'm not sure that's a huge risk anymore since you need the unique session token to get the user info. We can put out a patch later if needed.

File: utility/getToken/getToken.js (hunk 2 above)
Comment (Sidragon123) [reply utility/getToken/getToken.js]: Will work this in

File: Controllers/userController.js (hunk 1 above)
Comment (gbudjeakp) [reply Controllers/userController.js]: Hmmm do you mind doing one more thing? Can you research securing your redis cache instance and
let me know what you find? I don't mind patching later if its a bug but I don't want us to just 
allow a potential security flaw.

File: utility/getToken/getToken.js [hunk 3]
```diff
@@ -0,0 +1,9 @@
+const jwt = require("jsonwebtoken");
+const getToken = (req) => {
+  const { authToken } = req.cookies;
+  const { id, username } = jwt.verify(authToken, process.env.JWT_SECRET);
+  return [id, username];
```
Comment (gbudjeakp) [inline utility/getToken/getToken.js]: Let's modify this to return an object instead of an array

File: Controllers/userController.js [hunk 4]
```diff
@@ -149,13 +150,19 @@ const loginUser = async (req, res) => {
 //This logs the user out the app by removing the
 //Users token
 const logout = async (req, res) => {
+  const [id, username] = getToken.getToken(req);
```
Comment (gbudjeakp) [inline Controllers/userController.js]: Once you fix the get token then you can use destructuring to get 
Whichever one you want/need

File: Controllers/feedbackController.js [hunk 5]
```diff
@@ -14,14 +14,14 @@ const {
...
+const getToken = require("../utility/getToken/getToken");
 
 /*This controller allows the interns to request for feedback using the request
 feedback forms.
  */
 
 const submitFeedBack = async (req, res) => {
-  const { authToken } = req.cookies;
-  const { id } = jwt.verify(authToken, process.env.JWT_SECRET);
+  const [id, username] = getToken(req);
```
Comment (gbudjeakp) [inline Controllers/feedbackController.js]: We only need id here and not username. Once you tweak your getToken function, you can adjust this. We don't want to get the username where we don't need it

File: Controllers/userController.js [hunk 6]
```diff
@@ -181,9 +217,8 @@ const authorized = async (req, res) => {
 
 // This lets us update a users account information everywhere
 const updateAccount = async (req, res) => {
-  const { authToken } = req.cookies;
+  const [id, uName] = getToken(req);
```
Comment (gbudjeakp) [inline Controllers/userController.js]: This needs to be fixed.

File: Controllers/userController.js [hunk 7]
```diff
@@ -165,11 +172,40 @@ const logout = async (req, res) => {
 // the app know whether or not a user is logged in.
 const authorized = async (req, res) => {
   try {
-    let userInfo = await redisClient.GET("UserInfo");
+    const [token, uName] = getToken.getToken(req);
```
Comment (gbudjeakp) [inline Controllers/userController.js]: This needs to be fixed to match the change in get token function

File: Controllers/feedbackController.js [hunk 8]
```diff
@@ -212,9 +218,7 @@ for
 const assignFeedBack = async (req, res) => {
   try {
     const { feedbackrequestId } = req.params;
-    const { authToken } = req.cookies;
-    const { id, username } = jwt.verify(authToken, process.env.JWT_SECRET);
-
+    const { id, username } = getToken.getToken(req);
```
Comment (gbudjeakp) [inline Controllers/feedbackController.js]: We don't need getToken.getToken here

File: Controllers/feedbackController.js [hunk 9]
```diff
@@ -113,25 +119,26 @@ const getAllFeedBackRequestsForms = async (req, res) => {
 that is logged in */
 const getUserFeedBackRequestForms = async (req, res) => {
   try {
-    const redisResponse =
-      await redisFunctions.cacheGetUserFeedbackRequestForms();
+    const { id } = getToken.getToken(req);
```
Comment (gbudjeakp) [inline Controllers/feedbackController.js]: We don't need getToken.getToken here shouldn't this just be getToken?

File: Controllers/feedbackController.js [hunk 10]
```diff
@@ -83,7 +83,8 @@ const submitFeedBack = async (req, res) => {
  */
 const getAllFeedBackRequestsForms = async (req, res) => {
   try {
-    const redisResponse = await redisFunctions.cacheGetFeedbackRequestForms();
+    const { id } = getToken.getToken(req);
```
Comment (gbudjeakp) [inline Controllers/feedbackController.js]: No getToken.geToken here as well

File: Controllers/userController.js [hunk 11]
```diff
@@ -165,11 +172,40 @@ const logout = async (req, res) => {
 // the app know whether or not a user is logged in.
 const authorized = async (req, res) => {
   try {
-    let userInfo = await redisClient.GET("UserInfo");
+    const { token } = getToken(req);
```
Comment (gbudjeakp) [inline Controllers/userController.js]: Shouldn't this be id? Since you returned an  object if you want to call it token then it'd be
{token:  id}

**Review by gbudjeakp — APPROVED** [review]

**Review by gbudjeakp — APPROVED** [review]
